#!/bin/bash

# Setting up Environment
. ./env ${1} || exit 1;

echo "${bldcya}***** Final touch on kernel *****${txtrst}"

if [ -e $KERNELDIR/out/boot.img ]; then
rm -f $KERNELDIR/out/boot.img;
rm -f $KERNELDIR/out/*.tar;
rm -f $KERNELDIR/out/*.zip;
fi;

# Making the new kernel image... #
$KERNELDIR/scripts/mkbootimg --kernel $KERNELDIR/zImage --ramdisk $KERNELDIR/ramdisk.gz -o $KERNELDIR/boot.img --base 0x81600000 --ramdiskaddr 0x82600000

BUILDTIME=`date +"[%m-%d]-[%H-%M]"`

cp $KERNELDIR/boot.img /$KERNELDIR/out/
cd $KERNELDIR/out/

zip -r kernel-${BUILDTIME}.zip .

# Making Odin Flashable
tar cvf kernel-${BUILDTIME}.tar boot.img

echo "${bldcya}***** Done *****${txtrst}";
