#!/bin/bash

# Time of build startup
  res1=$(date +%s.%N)

  echo "${bldcya}***** Setting up Environment *****${txtrst}";
. ./env ${1} || exit 1;

if [ ! -f $KERNELDIR/.config ]; then
  echo "${bldcya}***** Writing Config *****${txtrst}";
  cp $KERNELDIR/arch/arm/configs/$KERNEL_CONFIG .config;
  make $KERNEL_CONFIG;
fi;

. $KERNELDIR/.config


# remove previous zImage files
if [ -e $KERNELDIR/zImage ]; then
  rm $KERNELDIR/zImage;
  rm $KERNELDIR/boot.img;
fi;

if [ -e $KERNELDIR/arch/arm/boot/zImage ]; then
  rm $KERNELDIR/arch/arm/boot/zImage;
fi;

# make zImage
  echo "${bldcya}***** Compiling kernel *****${txtrst}"

if [ $USER != "root" ]; then
  make -j$NUMBEROFCPUS
else
  nice -n -15 make -j$NUMBEROFCPUS
fi;

if [ -e $KERNELDIR/arch/arm/boot/zImage ]; then
  cp $KERNELDIR/arch/arm/boot/zImage $KERNELDIR/zImage;

  echo "${bldcya}***** Ready to Roar *****${txtrst}";
  res2=$(date +%s.%N)
  echo "${bldgrn}Total time elapsed: ${txtrst}${grn}$(echo "($res2 - $res1) / 60"|bc ) minutes ($(echo "$res2 - $res1"|bc ) seconds) ${txtrst}";	
else
  echo "${bldred}Kernel STUCK in BUILD!${txtrst}"
fi;
