#!/bin/bash

# Time of build startup
  res1=$(date +%s.%N)

# location
  export KERNELDIR=`readlink -f .`;
  export PARENT_DIR=`readlink -f ${KERNELDIR}/..`;

# link modules to parent directory
  ln -s $KERNELDIR/modules $PARENT_DIR/modules

# name
  export KBUILD_BUILD_USER=mohammad.afaneh
  export KBUILD_BUILD_HOST=ubuntu

  export ARCH=arm
  export CROSS_COMPILE=~/kernel/arm-eabi-4.4.3/bin/arm-eabi-
  make bcm21553_totoro_05_defconfig

# remove previous zImage files
if [ -e $KERNELDIR/zImage ]; then
  rm $KERNELDIR/zImage;
fi;

if [ -e $KERNELDIR/arch/arm/boot/zImage ]; then
  rm $KERNELDIR/arch/arm/boot/zImage;
fi;

# number of cpus
export NUMBEROFCPUS=`grep 'processor' /proc/cpuinfo | wc -l`;

# make zImage
  echo "${bldcya}***** Compiling kernel *****${txtrst}"

if [ $USER != "root" ]; then
  make -j$NUMBEROFCPUS zImage
else
  nice -n -15 make -j$NUMBEROFCPUS zImage
fi;

if [ -e $KERNELDIR/arch/arm/boot/zImage ]; then
  cp $KERNELDIR/arch/arm/boot/zImage $KERNELDIR/zImage;
  echo "${bldcya}***** Ready to Roar *****${txtrst}";
  res2=$(date +%s.%N)
  echo "${bldgrn}Total time elapsed: ${txtrst}${grn}$(echo "($res2 - $res1) / 60"|bc ) minutes ($(echo "$res2 - $res1"|bc ) seconds) ${txtrst}";	
else
  echo "${bldred}Kernel STUCK in BUILD!${txtrst}"
fi;
