#!/bin/bash

# Setting up Environment
. ./env ${1} || exit 1;

echo "${bldcya}***** Cleaning in Progress *****${txtrst}";

make distclean;
make clean;
rm -f $KERNELDIR/zImage;
rm -f $KERNELDIR/boot.img;
rm -f $KERNELDIR/out/boot.img;
rm -f $KERNELDIR/out/*.tar;
rm -f $KERNELDIR/out/*.zip;

echo "${bldcya}***** Cleaning Done *****${txtrst}";
